### ISSUE TITLE
Suggestion: Highlight correct answer as green if wrong answer was selected.

### ISSUE THREAD

**Issue by ukfhVp0zms** [cwitmer34/milestone-one#3]
While highlighting the wrong answer as red, also highlight correct answer as green (or another color that signifies the correct answer). This could help the user learn some trivia knowledge, even if they got it wrong.

**Comment by cwitmer34** [comment]
I love this! I'll add it in the next patch that I deploy in a few days! @ukfhVp0zms thanks so much, whoever this is!
